import{i as n,S as l}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const c="https://pixabay.com/api/",u="46110623-cffeede45492ee1adb33fe3c4";function f(t){const o=new URLSearchParams({key:u,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true"});return fetch(`${c}?${o}`).then(r=>{if(!r.ok)throw new Error("Failed to fetch images");return r.json()}).then(r=>{if(r.hits.length===0)throw new Error("No images found");return r.hits})}const m=t=>{const o=document.querySelector(".gallery");if(o.innerHTML="",images.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const r=t.reduce((i,e)=>i+`<div class="gallery-item">
                <a href="${e.largeImageURL}" class="gallery-link">
                 <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" />
                 </a>
                 <ul class="info">
                    <li class="info-item">Likes: ${e.likes}</li>
                    <li class="info-item">Views: ${e.views}</li>
                    <li class="info-item">Comments: ${e.comments}</li>
                    <li class="info-item">Downloads: ${e.downloads}</li>
                 </ul>
            </div>`,"");o.innerHTML=r},d=()=>{const t=document.querySelector(".loader");t.style.display="block"},g=()=>{const t=document.querySelector(".loader");t.style.display="none"},y=document.querySelector(".search-form"),h=new l(".gallery a",{captions:!0,captionDelay:250});y.addEventListener("submit",t=>{t.preventDefault();const o=t.target.elements.query.value.trim();o&&(d(),f(o).then(r=>{m(r),h.refresh()}).catch(r=>{n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}).finally(()=>{g()}))});
//# sourceMappingURL=index.js.map
