import{i as n,S as l}from"./assets/vendor-5ObWk2rO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const c="https://pixabay.com/api/",u="46110623-cffeede45492ee1adb33fe3c4",m=r=>{const t=new URLSearchParams(r);return fetch(`${c}?key=${u}&${t}`).then(o=>{if(!o.ok)throw new Error("Sorry, there are no images matching your search query. Please try again!");return o.json()}).then(o=>o.hits)},d=r=>{const t=document.querySelector(".gallery");if(t.innerHTML="",images.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const o=r.reduce((a,e)=>a+`<div class="gallery-item">
                <a href="${e.largeImageURL}" class="gallery-link">
                 <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-image" />
                 </a>
                 <ul class="info">
                    <li class="info-item">Likes: ${e.likes}</li>
                    <li class="info-item">Views: ${e.views}</li>
                    <li class="info-item">Comments: ${e.comments}</li>
                    <li class="info-item">Downloads: ${e.downloads}</li>
                 </ul>
            </div>`,"");t.innerHTML=o},f=()=>{const r=document.querySelector(".loader");r.style.display="block"},y=()=>{const r=document.querySelector(".loader");r.style.display="none"},g=document.querySelector(".search-form"),h=new l(".gallery a",{captions:!0,captionDelay:250});g.addEventListener("submit",r=>{r.preventDefault();const t=r.target.elements.query.value.trim();t&&(f(),m(t).then(o=>{d(o),h.refresh()}).catch(o=>{iziToast.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}).finally(()=>{y()}))});
//# sourceMappingURL=index.js.map
